---
- hosts: kv
  vars:
    cassandra_home: /opt/apache-cassandra
  tasks:
  - name: creating a temporary directory
    tempfile:
      state: directory
    register: temp

  - name: archiving the database logs
    archive:
      path: "{{ cassandra_home }}/logs"
      dest: "{{ temp.path }}/{{ inventory_hostname }}.zip"
      format: zip

  - name: downloading the remote logs
    fetch:
      src: "{{ temp.path }}/{{ inventory_hostname }}.zip"
      dest: ../
      flat: yes

  - name: removing temporary files
    file: path={{ temp.path }} state=absent
