---
- hosts: kv:index:n1ql:analytics
  vars:
    data_dir: /data
    disk: /dev/sdb1
    opts: ""
    to_trim: 1
  tasks:
  - name: umounting data parition
    mount:
      name: "{{ data_dir }}"
      state: unmounted
      src: "{{ disk }}"
      fstype: "{{ fstype | default('ext4') }}"

  - name: re-creating filesystem
    filesystem:
      fstype: "{{ fstype | default('ext4') }}"
      dev: "{{ disk }}"
      opts: "{{ opts }}"
      force: yes

  - name: mounting data parition
    mount:
      name: "{{ data_dir }}"
      state: mounted
      src: "{{ disk }}"
      fstype: "{{ fstype | default('ext4') }}"

  - name: discarding unused blocks
    shell: fstrim -v {{ data_dir }}
    when: to_trim == 1
